easy_admin:
    site_name: 'LOCKIO'
    entities:
        # List the entity class name you want to manage
        - App\Entity\Country
        - App\Entity\User
        - App\Entity\Organization
        - App\Entity\StorageObject
