security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: App\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/

            anonymous: true

            form_login:
                check_path: login
                login_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: app_bucket

            logout:
                path: logout
                target: app_homepage

            guard:
                authenticators:
                - App\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/bucket, roles: ROLE_USER }
        - { path: ^/invoices, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/payment-settings, roles: ROLE_USER }